name: Terraform Apply

on:
  push:
    branches:
      - main
      - staging
      - production

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          tf_version: 0.14.9

      - name: Authenticate with GCP
        run: echo "$GCP_SERVICE_ACCOUNT_KEY" | base64 -d > /tmp/gcp-key.json && gcloud auth activate-service-account --key-file=/tmp/gcp-key.json

      - name: Select Workspace
        run: terraform workspace select ${{ github.event_name }}

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Apply
        run: terraform apply -auto-approve

